homeassistant:
  name: !secret homeassistant_name
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customize.yaml

frontend:

config:

http:
  api_password: !secret http_api_password
  trusted_networks: 
    - 10.0.0.0/24
    - 192.168.0.0/16
    - 127.0.0.1
  use_x_forwarded_for: True

updater:

discovery:
  ignore:
    - samsung_tv

conversation:

history:

recorder:
  purge_keep_days: 1
  purge_interval: 4
  exclude: 
    entities:
      - sun.sun
      - sensor.last_boot
      - sensor.date

logbook:

sun:

input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml

sensor:
  - platform: yr
  - platform: moon
  - platform: time_date
    display_options:
      - 'time'

zwave: 
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_network_key
  device_config: !include zwave_device_config.yaml

hue:
  bridges:
    - host: 192.168.0.111
      allow_unreachable: true
      allow_hue_groups: true


device_tracker: !include device_tracker.yaml

tts:
  platform: google

group: !include groups.yaml

script: !include scripts.yaml

automation: !include automations.yaml
