
jos_telefon:
  hide_if_away: false
  icon: mdi:cellphone-wireless
  mac: !secret jos_telefon_mac 
  name: Jos telefon
  picture:
  track: true
  vendor: Murata Manufacturing Co., Ltd.

grys_telefon:
  hide_if_away: false
  icon: mdi:cellphone-wireless
  mac: !secret grys_telefon_mac
  name: Grys telefon
  picture:
  track: true
  vendor: unknown
